TaskManager/Controllers/DeveloperController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Data;
using DataAccess.IRepository;
using DataAccess.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;

namespace TaskManager.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly ILogger<DeveloperController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public DeveloperController(ILogger<DeveloperController> logger,
            IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        public IActionResult Index()
        {
            IEnumerable<Developer> developers = _unitOfWork.Developers.GetAll()
                .OrderByDescending(d => d.CreatedAt)
                .Where(d => d.Status != 404);
            return View(developers);
        }

        // client-side
        // public IActionResult LoadDevList() {
        //     IEnumerable<Developer> developers = _unitOfWork.Developers.GetAll()
        //         .OrderByDescending(d => d.CreatedAt)
        //         .Where(d => d.Status != 404);
        //     return Json(new { data = developers});
        // }

        [HttpPost]
        public JsonResult GetDevList(int draw, int start, int length, string filter_keywords, int filter_option = 0)
        {
            int totalRecord = 0;
            int filterRecord = 0;

            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            var data = _unitOfWork.Developers.GetAll().Where(d => d.Status != 404);

            //get total count of data in table
            totalRecord = data.Count();

            if (!string.IsNullOrEmpty(filter_keywords))
            {
                data = data.Where(d => d.Name.ToLower().Contains(filter_keywords.ToLower()))
                .Where(d => d.Status != 404);
            }
            if (filter_option != 0)
            {
                data = data.Where(d => d.Status == filter_option)
                .Where(d => d.Status != 404);
            }

            // get total count of records after search 
            filterRecord = data.Count();

            //pagination
            var devList = data.Skip(start).Take(length)
                .OrderByDescending(d => d.CreatedAt).ToList().Where(d => d.Status != 404);

            List<object> dataList = new List<object>();
            foreach(var item in devList)
            {
                string actionLink = $"<div class='w-75 btn-group' role='group'>" +
                    $"<a href='Developer/Edit/{item.Id}'" +
                    $"class='btn btn-primary mx-2'><i class='bi bi-pencil-square'></i>Edit</a>" +
                    $"<button data-bs-target='#deleteDev' data-bs-toggle='ajax-modal' class='btn btn-danger mx-2 btn-delete'" +
                    $"data-dev-id='{item.Id}'>Delete</button><a href='Developer/Details/{item.Id}' class='btn btn-secondary mx-2'>" +
                    $"<i class='bi bi-trash-fill'></i>Details</a></div>";
                string statusConditionClass = item.Status == 1 ? "text-success" : "text-danger";
                string statusConditionText = item.Status == 1 ? "Active" : "Inactive";
                string status = $"<span class='{statusConditionClass}'>{statusConditionText}</span>";

                // Dictionary<string, string> dataItems = new Dictionary<string, string>();
                // dataItems.Add("name", item.Name);
                // dataItems.Add("status", status);
                // dataItems.Add("CustomStatus", item.Status == 1 ? "Active": "Inactive");
                // dataItems.Add("action", actionLink);

                List<string> dataItems = new List<string>();
                dataItems.Add(item.Name);
                dataItems.Add(status);
                dataItems.Add(actionLink);
                
                dataList.Add(dataItems);
            }

            var returnObj = new { draw = draw, recordsTotal = totalRecord,
                recordsFiltered = filterRecord, data = dataList };
            return Json(returnObj);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Developer developer)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Developers.Add(developer);
                _unitOfWork.Save();
                TempData["success"] = "Developer created successfully!";
                return RedirectToAction("Index");
            }
            return View(developer);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var developer = _unitOfWork.Developers.GetFirstOrDefault(d => d.Id == id);
            if (developer == null || developer.Status == 404)
            {
                return NotFound();
            }
            return View(developer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Developer developer)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Developers.Update(developer);
                _unitOfWork.Save();
                TempData["success"] = "Developer updated successfully!";
                return RedirectToAction("Index");
            }
            return View(developer);
        }

        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var developer = _unitOfWork.Developers.GetFirstOrDefault(d => d.Id == id);
            if (developer == null || developer.Status == 404)
            {
                return NotFound();
            }
            return PartialView("_DevDeletePartial", developer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid? id)
        {
            var developer = _unitOfWork.Developers.GetFirstOrDefault(d => d.Id == id);
            if (developer == null || developer.Status == 404)
            {
                return NotFound();
            }
            developer.Status = 404;
            _unitOfWork.Developers.Update(developer);
            _unitOfWork.Save();
            TempData["success"] = "Developer deleted successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid? id)
        {
            if (id == null) return NotFound();
            var developer = _unitOfWork.Developers.GetAll().FirstOrDefault(d => d.Id == id);
            if (developer == null || developer.Status == 404) return NotFound();
            return View(developer);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

TaskManager/Controllers/QAController.cs
using DataAccess.Data;
using DataAccess.IRepository;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace TaskManager.Controllers
{
    public class QAController : Controller
    {
        private readonly ILogger<QAController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public QAController(ILogger<QAController> logger,
            IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        public IActionResult Index()
        {
            IEnumerable<QA> qAs = _unitOfWork.QAs.GetAll()
                .Where(d => d.Status != 404)
                .OrderByDescending(q => q.CreatedAt);
            return View(qAs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(QA qA)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.QAs.Add(qA);
                _unitOfWork.Save();
                TempData["success"] = "QA Eng. created successfully!";
                return RedirectToAction("Index");
            }
            return View(qA);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var qA = _unitOfWork.QAs.GetFirstOrDefault(q => q.Id == id);
            if (qA == null || qA.Status == 404)
            {
                return NotFound();
            }
            return View(qA);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(QA qA)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.QAs.Update(qA);
                _unitOfWork.Save();
                TempData["success"] = "QA Eng. updated successfully!";
                return RedirectToAction("Index");
            }
            return View(qA);
        }

        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var qA = _unitOfWork.QAs.GetFirstOrDefault(q => q.Id == id);
            if (qA == null || qA.Status == 404)
            {
                return NotFound();
            }
            return PartialView("_QADeletePartial", qA);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid? id)
        {
            var qA = _unitOfWork.QAs.GetFirstOrDefault(q => q.Id == id);
            if (qA == null || qA.Status == 404)
            {
                return NotFound();
            }
            qA.Status = 404;
            _unitOfWork.QAs.Update(qA);
            _unitOfWork.Save();
            TempData["success"] = "QA Eng. deleted successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid? id)
        {
            if (id == null) return NotFound();
            var qA = _unitOfWork.QAs.GetFirstOrDefault(q => q.Id == id);
            if (qA == null || qA.Status == 404) return NotFound();
            return View(qA);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

TaskManager/Views/Shared/_DevDeletePartial.cshtml
@model Developer

<div class="modal fade" id="deleteDev" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteDevLabel">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-12">
                    <form method="post"
                          asp-action="Delete">
                        <input asp-for="Id" hidden />
                        <fieldset>
                            <div class="alert alert-danger" role="alert">
                                Are you sure you want to delete @Model.Name?
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-save="modal">Delete</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha384-xeJqLiuOvjUBq3iGOjvSQSIlwrpqjSHXpduPd6rQpuiM3f5/ijby8pCsnbu5S81n" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.32/sweetalert2.min.css" integrity="sha512-doewDSLNwoD1ZCdA1D1LXbbdNlI4uZv7vICMrzxfshHmzzyFNhajLEgH/uigrbOi8ETIftUGBkyLnbyDOU5rpA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManager.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Menu</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-controller="Developer" asp-action="Index" class="nav-link align-middle px-0">
                                <span class="ms-1 d-none d-sm-inline">Manage Developer</span>
                            </a>
                            <a asp-controller="QA" asp-action="Index" class="nav-link align-middle px-0">
                                <span class="ms-1 d-none d-sm-inline">Manage QA Eng.</span>
                            </a>
                            <a href="#" class="nav-link align-middle px-0">
                                <span class="ms-1 d-none d-sm-inline">More...</span>
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="col py-3">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/modal.js" asp-append-version="true"></script>
    <script src="~/js/dataTable.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.32/sweetalert2.min.js" integrity="sha512-yc+tEbvC4kiy3J6e0aZogFVr8AZhMtJTof2z+fGPaJgjehpIPzguZxfRRTiQcXlSHbJsB3Bborvv++81TMLZ2w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManager/Views/Shared/_QADeletePartial.cshtml
@model QA

<div class="modal fade" id="deleteQA" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteQALabel">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-12">
                    <form method="post"
                          asp-action="Delete">
                        <input asp-for="Id" hidden />
                        <fieldset>
                            <div class="alert alert-danger" role="alert">
                                Are you sure you want to delete @Model.Name?
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-save="modal">Delete</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>